kind: pipeline
name: test

steps:
- name: black
  image: cytopia/black:latest-0.2
  commands:
  - black --check .

- name: flake8
  image: alpine/flake8:3.7.8
  commands:
  - flake8

- name: pytest
  image: vmck/vagrant-vmck:0.3.0
  environment:
    CODECOV_TOKEN:
      from_secret: codecov_token

  commands:
  - export VMCK_URL=http://$VMCK_IP:$VMCK_PORT
  - echo $VMCK_IP
  - export VMCK_NAME="drone $DRONE_REPO:$DRONE_BRANCH#$DRONE_BUILD_NUMBER"
  - cp examples/.env ./
  - echo CODECOV_TOKEN=$CODECOV_TOKEN >> .env

---
kind: pipeline
name: publish

trigger:
  status:
  - success
  event:
  - push
  - tag

depends_on:
- test

steps:
- name: docker push branch ${DRONE_COMMIT_BRANCH}
  image: plugins/docker
  environment:
    DRONE_SECRET_PLUGIN_ENDPOINT: http://10.42.1.2:3000 
    DRONE_SECRET_PLUGIN_TOKEN: f7bafea3a8495410ced1cfa191edf094
  settings:
    tags: ${DRONE_COMMIT_BRANCH}
    repo: vmck/acs-interface
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    event:
    - push

- name: docker push autotag + latest
  image: plugins/docker
  settings:
    repo: vmck/acs-interface
    auto_tag: true
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
