kind: pipeline
name: test

---
kind: pipeline
name: publish

trigger:
  status:
  - success
  event:
  - push
  - tag

depends_on:
- test

steps:
- name: docker push branch ${DRONE_COMMIT_BRANCH}
  image: plugins/docker
  environment:
    DRONE_SECRET_PLUGIN_ENDPOINT: http://10.42.1.2:3000
    DRONE_SECRET_PLUGIN_TOKEN: f7bafea3a8495410ced1cfa191edf094
  settings:
    tags: ${DRONE_COMMIT_BRANCH}
    repo: vmck/acs-interface
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    event:
    - push

- name: docker push autotag + latest
  image: plugins/docker
  settings:
    repo: vmck/acs-interface
    auto_tag: true
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
